---
title: "Graphically Exploring Black Friday Data"
author: "Soumya Das"
date: "April 8, 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r libraries, echo=FALSE, results='hide', message=FALSE, warning=FALSE}

library(dplyr)
library(kableExtra)
library(knitr)
library(plotly)
library(ggplot2)
#install.packages("wesanderson")
library(wesanderson)

```


```{r blackfriday, echo=FALSE, results='asis', message=FALSE, warning=FALSE}

#reading the file from dell
#black_friday=read.csv("/home/soumya/Desktop/gitrepo/Business-Analytics/business_datasets/BlackFriday.csv")
#reading the file from lenovo
black_friday=read.csv("C:/Users/sdas/Desktop/myprojects/Business-Analytics/business_datasets/BlackFriday.csv")


##################################graphically exploring#########################################
#black_friday[,c(1,12)]

purchase_user=aggregate(Purchase~User_ID,black_friday[,c(1,12)],FUN = sum)

#purchase_user$User_ID<- factor(purchase_user$User_ID, levels = unique(purchase_user$User_ID)[order(purchase_user$Purchase, decreasing = F)])
purchase_user=purchase_user[order(-purchase_user$Purchase),]


kable(purchase_user[1:5,],caption = "Top Purchasing User-ID") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

options("scipen"=100, "digits"=4)
hist(purchase_user[,2],col="steelblue",main="Purchasing Range of Consumers",
xlab="Purchase($)",ylab ="People Count" )

#number of times a user_id bought products
userid_count= as.data.frame(table(black_friday[,1])) 
userid_count=userid_count[order(-userid_count$Freq),]
colnames(userid_count)[1]="User_ID"

kable(userid_count[1:5,],caption = "Top 5 User-IDs purchasing the most") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

#ggplot(data=userid_count, aes(x=User_ID, y=Freq)) +
#  geom_bar(stat="identity",fill="steelblue")


##################################PRODUCT ANALYSIS######################


#number of times a product_id was purchased
productid_count= as.data.frame(table(black_friday[,2]))
productid_count=productid_count[order(-productid_count$Freq),]
colnames(productid_count)[1]="Product_ID"

kable(productid_count[1:5,],caption = "Top 5 Product-IDs which were purchased most") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

product_price=aggregate(Purchase~Product_ID,data = black_friday,FUN = sum)

product_list=left_join(product_price,productid_count,by='Product_ID')
colnames(product_list)[2]='NetSales'
colnames(product_list)[3]='Quantity'
product_list$Average_Sales=product_list$NetSales/product_list$Quantity


kable(product_list[1:5,],caption = "Product List") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

ggplot(product_list, aes(x=Quantity, y=NetSales)) + geom_point() + labs(title="NetSales vs. Quantity")

ggplot(product_list, aes(x=NetSales, y=Quantity)) + geom_point() + geom_smooth(method=lm) + labs(title="NetSales vs. Quantity, adding the Regression Line")

#ggplot(data=productid_count, aes(x=Product_ID, y=Freq)) +
#  geom_bar(stat="identity",fill="steelblue")


##head(table(black_friday[,c(2,3)]))

###########################################CUSTOMER ANALYSIS##########################################

###########################Number of Male and Female customers from different age group#######################

#head(table(black_friday[,c(4,3)]))
customers=unique(black_friday[,c(1,3,4,5,6,8)])
customers_agegender=as.data.frame(table(customers[,c(3,2)])) 

summary(customers$Age)
#gender_age_wide=as.data.frame(reshape(gender_age,idvar = 'Age',timevar = 'Gender',direction = "wide"))

ggplot(data=customers_agegender, aes(x=customers_agegender$Age, y=customers_agegender$Freq, fill=customers_agegender$Gender)) +
    geom_bar(stat="identity", position=position_dodge())+scale_fill_hue(name="Gender") +      
    xlab("Age") + ylab("People Count") + 
    ggtitle("Number of Participants per Gender")

customerage_city=as.data.frame(table(customers[,c(3,5)])) 

#grouped barchart
ggplot(customerage_city, aes(x=Age, y=Freq,fill=City_Category)) + labs(title="Number of People per Age group in each city") + geom_bar(stat="identity",position=position_dodge()) 

#stacked barchart
ggplot(customerage_city, aes(x=Age, y=Freq,fill=City_Category)) + labs(title="Number of People per Age group in each city") + geom_bar(stat="identity") 

##there are more people in city C
 


#which city has most number of youngsters , i.e people between 26-35 : city A
ggplot(customerage_city, aes(x=City_Category, y=Freq,fill=Age)) + labs(title="Number of People per Age group in each city") + geom_bar(stat="identity",position=position_dodge())


# df=customers[,c(3,5)]
# 
# df_prop <- df %>% 
#   count(Age,City_Category) %>%            # group_by() & summarise(n = n()) are implicit
#   mutate(prop = prop.table(n)*100)
# 
# ggplot(df_prop, aes(x=City_Category, y=prop,fill=Age)) + labs(title="Number of People per Age group in each city") + geom_bar(stat="identity",position=position_dodge())


customerage_city$Percent[customerage_city$City_Category=='A']=customerage_city$Freq[customerage_city$City_Category=='A']/sum(customerage_city$Freq[customerage_city$City_Category=='A'])*100

customerage_city$Percent[customerage_city$City_Category=='B']=customerage_city$Freq[customerage_city$City_Category=='B']/sum(customerage_city$Freq[customerage_city$City_Category=='B'])*100

customerage_city$Percent[customerage_city$City_Category=='C']=customerage_city$Freq[customerage_city$City_Category=='C']/sum(customerage_city$Freq[customerage_city$City_Category=='C'])*100

ggplot(customerage_city, aes(x=City_Category, y=Percent,fill=Age)) + labs(title="Number of People per Age group in each city") + geom_bar(stat="identity",position=position_dodge())

#which age group has most purchasing capability?
tpurchase_agegroup=aggregate(Purchase~Age,black_friday[,c(4,12)],FUN = sum)
purchasecount_agegroup=as.data.frame(table(black_friday[,4]))
colnames(purchasecount_agegroup)[1]='Age'
averagepurchase_agegroup=left_join(tpurchase_agegroup,purchasecount_agegroup,by='Age')
##how much the age group spend on their each buying in average
averagepurchase_agegroup$Avg_Purchase=averagepurchase_agegroup$Purchase/averagepurchase_agegroup$Freq


averagepurchase_agegroup$Age <- factor(averagepurchase_agegroup$Age, levels = unique(averagepurchase_agegroup$Age)[order(averagepurchase_agegroup$Purchase, decreasing = FALSE)])

kable(averagepurchase_agegroup,caption = "Average Purchase per Agegroup") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

ggplot(data=averagepurchase_agegroup, aes(x=Age, y=Purchase)) + labs(title="Total Spending on Purchase per Age Group") +
  geom_bar(stat="identity",fill="steelblue")+ coord_flip()


##this is how we extract the valuable information from our data and segment the market
# purchase_group=aggregate(Purchase~Age+Gender+Marital_Status+City_Category,data = black_friday,FUN = sum)
# 
# ggplot(purchase_group[purchase_group$City_Category == 'A', ], 
#   aes(x = Purchase)) + labs(title="Purchasing capability of People from city A") +
#   geom_density(fill = 'blue', alpha=0.4) + 
#   geom_vline(aes(xintercept=median(Purchase, na.rm=T)),
#     colour='red', linetype='dashed', lwd=1)
# 
# 
# ggplot(purchase_group[purchase_group$City_Category == 'B', ], 
#   aes(x = Purchase)) + labs(title="Purchasing capability of People from city B") +
#   geom_density(fill = '', alpha=0.4) + 
#   geom_vline(aes(xintercept=median(Purchase, na.rm=T)),
#     colour='red', linetype='dashed', lwd=1)
# 
# 
# ggplot(purchase_group[purchase_group$City_Category == 'C', ], 
#   aes(x = Purchase)) + labs(title="Purchasing capability of People from city C") +
#   geom_density(fill = 'orange', alpha=0.4) + 
#   geom_vline(aes(xintercept=median(Purchase, na.rm=T)),
#     colour='red', linetype='dashed', lwd=1)
# #######Marital_Age###dataset
#black_friday$Marital_Status=as.character(black_friday$Marital_Status)
ggplot(black_friday[,c(4,12)],aes(x=Age,y=Purchase))+geom_boxplot() + labs(title="Amount Spend on transactions in average by people from each age group")

ggplot(black_friday[,c(6,12)],aes(x=City_Category,y=Purchase))+geom_boxplot() + labs(title="Amount Spend on transactions in average by people from each city")


```